### PR TITLE
Fix races in subscription.go

### PR DESCRIPTION
**Pull request by foreverest**
This patch fixes the races that occur when using `SubscriptionClient`.

@dmitshur we'd love to use this lib at Reddit but it has race conditions, currently. Could you take a look at this, please?

### CODE REVIEW

**Comment by hgiasac** [comment]
Hi @foreverest 
There is a merged PR that fix this issue using atomic lock. https://github.com/hasura/go-graphql-client/commit/408d1f23326fe1fb2ab649fbb2531d4c390bf64a

Can you please verify if it solves your issue. If it works, we can close this PR

Best!

**Comment by foreverest** [comment]
@hgiasac I guess you linked a wrong commit?

**Comment by hgiasac** [comment]
@foreverest Sorry. This is the correct commit https://github.com/hasura/go-graphql-client/commit/5371adce8738708814c2c925fa00437951802ca0

**Comment by jeanlucmongrain** [comment]
please rebase

**Comment by davitovmasyan** [comment]
Please also check this https://github.com/hasura/go-graphql-client/pull/27

**Comment by jflambert** [comment]
Hi @foreverest  and @hgiasac  what's the status here? Want to use go-graphql-client in production and I want to be aware of any outstanding issues.

**Comment by hgiasac** [comment]
The issue was fixed by #27. We can close this

**Pull request closed without merging**
