### PR TITLE
Allow to set custom *http.Client in SubscriptionClient

### PR DESCRIPTION
**Pull request by Difrex**
Hello.

This patch adds support to set up a custom `*http.Client`.  This needs, for example, if you are using an oauth2 authorization.

### CODE REVIEW

**Comment by bclermont** [comment]
this PR is outdated, as this feature already exists

**Comment by Difrex** [comment]
I don't see this feature in the subscriptions client.

**Comment by hgiasac** [comment]
@bclermont means we can set custom websocket client with this method https://github.com/hasura/go-graphql-client/blob/408d1f23326fe1fb2ab649fbb2531d4c390bf64a/subscription.go#L136

```go
func (sc *SubscriptionClient) WithWebSocket(fn func(sc *SubscriptionClient) (WebsocketConn, error)) *SubscriptionClient
```

Therefore should we need to add this option, or just improve the docs about how to customize the websocket client

**Comment by hgiasac** [comment]
IMO there are more configurations that can be customized in the WebSocket client, not only `http.Client`
So it's better to expose the `WebsocketHandler`, and we just need to rewrite the constructor for custom client https://github.com/hasura/go-graphql-client#custom-websocket-client

Thank you for your contribution. However we can close this PR

**Pull request closed without merging**
